export const HttpStatusMessage = {
  NOT_FOUND: 'NOT_FOUND',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  ALREADY_EXISTS: 'ALREADY_EXISTS',
  BAD_REQUEST: 'BAD_REQUEST',
  NOT_ACCEPTABLE: 'NOT_ACCEPTABLE',
  EXPIRED_TIME: 'EXPIRED_TIME',
  UNAUTHORIZED: 'UNAUTHORIZED',
  OTP_NOT_MATCHED: 'OTP_NOT_MATCHED',
};
